### ISSUE TITLE
addon failing if Mirror Modifier name is non-default

### ISSUE THREAD

**Issue by g3ntile** [walterpalladino/applyMirrorAndSeparate#1]
Hi! I noticed that the addon checks for the **name** of the modifier to be "Mirror", instead of the type. 
This way, if the modifier gets renamed (because you renamed it explicitly, or it was generated by another addon –that usually give modifiers funny custom names– it fails to recognize the modifier and fails. 
You can replace line 50 with:

`if (modifier.type == 'MIRROR'):
`
So that it checks for the type of modifier instead of the name.
I was making a pull request, but it looks like too much hassle, and I still don't fully grasp how github work for collaboration, and, it's just one line of code.
Test it and see if you like it!

**Comment by walterpalladino** [comment]
Good point, I fixed it.
Thank You.
Walter--
